version: '3'
services:
  web:
    build: .
    volumes:
      - ./app/:/app/
    ports:
      - ${APP_PUBLIC_PORT}:8000
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    command: postgres -c max_connections=100
    image: postgres:10.12
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    # all environment variables are defined in below file.
    env_file:
      - ./.env